### PR TITLE
Update deku to 0.17.0

### PR DESCRIPTION
**Pull request by wcampbell0x2a**
See https://github.com/sharksforarms/deku/releases/tag/deku-v0.17.0

### CODE REVIEW

**Comment by jessebraham** [comment]
Thanks for the PR. I guess we will need to bump the MSRV to `1.71.0` to get CI green, if you wouldn't mind making those changes.

**Comment by wcampbell0x2a** [comment]
> Thanks for the PR. I guess we will need to bump the MSRV to `1.71.0` to get CI green, if you wouldn't mind making those changes.

Sure, pushed updates to do that.

**Comment by MabezDev** [comment]
@wcampbell0x2a You also need to bump the MSRV inside the CI workflow to get it passing :)

**Comment by wcampbell0x2a** [comment]
> @wcampbell0x2a You also need to bump the MSRV inside the CI workflow to get it passing :)

done

**Review by jessebraham — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
